### ISSUE TITLE
[Help Wanted] Beta Testers!

### ISSUE THREAD

**Issue by mAAdhaTTah** [mAAdhaTTah/wp-gistpen#142]
If you're interested in testing WP-Gistpen, comment below and let me know you're using the plugin. You can download the current release [on the releases page](https://github.com/mAAdhaTTah/wp-gistpen/releases). The releases are built and deployed automatically with travis, so they'll show up when I tag them. You should download the `.zip` file for a given release and upload it to your WordPress site.

If you have questions or suggestions for the testing process, would love to hear them in this thread.

Thanks for contributing!

**Comment by miklb** [comment]
I'm in. Only thing I'm not following so far is are the gists supposed to be displayed on the front end or do they need to be inserted into a post to be viewable?

**Comment by cjwd** [comment]
Just installed it, taking it for a spin

**Comment by mAAdhaTTah** [comment]
@cjwd Hey, sorry, just saw ur edit. That problem should be fixed in the latest beta. If you run into anything else, definitely open a new issue. Thanks!

**Comment by mAAdhaTTah** [comment]
Thank you both for your help! I'm going to close this issue, as I'm going to release this to WP.org soon, so you'll be able to get the latest version directly from there as well.
