### ISSUE TITLE
Load JS in footer?

### ISSUE THREAD

**Issue by miklb** [mAAdhaTTah/wp-gistpen#169]
Wondering if the js file could be loaded in the footer, or at least conditionally loaded only on the `post type gistpen`

When I was doing a general performance audit it came up while checking my home page where I'm currently not showing any gists. Just a thought. Otherwise, beta still looking good.

**Comment by mAAdhaTTah** [comment]
I'll take a look at loading the web facing js in the footer (can't remember the reason I did it that way offhand), but I don't think we can conditionally load it because the shortcode isn't specific to a given post type.

**Comment by miklb** [comment]
Ah,that makes sense. If it can be, that would be great, if not, there are plenty of other areas for me to optimize performance. thanks!

**Comment by mAAdhaTTah** [comment]
Fixed by #170.
