### ISSUE TITLE
WPUpdatePhp Library out of date

### ISSUE THREAD

**Issue by AramZS** [mAAdhaTTah/wp-gistpen#199]
Latest version of WPUpdatePhp at https://github.com/WPupdatePHP/wp-update-php/blob/master/src/WPUpdatePhp.php has additional options available. As a result the out of date library can cause some conflicts with other plugins relying on previously initiated versions of the library to match signature.

**Comment by mAAdhaTTah** [comment]
Oh, the wild world of WordPress dependency management.

**Comment by mAAdhaTTah** [comment]
I think I've got [the latest version](https://github.com/mAAdhaTTah/wp-gistpen/blob/develop/composer.lock#L98)... Can you double check you've got the latest version of WP-Gistpen?

**Comment by mAAdhaTTah** [comment]
If you have the version currently on .org, then when this goes out (hopefully sometime this week), this should be resolved.
