### ISSUE TITLE
Should be using "cmb2_before_{$object_type}_form_{$this->cmb_id}" instead of 'cmb2_before_form'

### ISSUE THREAD

**Issue by jtsternberg** [mAAdhaTTah/WP-Gistpen#27]
The gistpen output is leaking onto other metaboxes: http://b.ustin.co/FhpO

**Comment by jtsternberg** [comment]
Hooks is found here: https://github.com/WebDevStudios/CMB2/blob/master/CMB2.php#L186

Looks like your hook name should be `cmb2_before_options-page_form_wpgp_option_metabox`

**Comment by mAAdhaTTah** [comment]
Thanks for reporting.

**Comment by jtsternberg** [comment]
:+1:
