### ISSUE TITLE
Error when trying to import from Git

### ISSUE THREAD

**Issue by alexanderdejong** [mAAdhaTTah/WP-Gistpen#289]
Hi there, when I press Dispatch Job in import I receive the following error in console. 

Any ideas on how to fix this? -- My account is connected so that works!

Cheers,
Alexander

`fail.js:2 Uncaught TypeError: [tcomb] Invalid value [object Object] supplied to evt$ (expected a Observable)
    at Function.fail (fail.js:2)
    at Jobs__assert (Jobs.js:47)
    at onClick (Jobs.js:23)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at Object.invokeGuardedCallback (react-dom.development.js:187)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:201)
    at executeDispatch (react-dom.development.js:461)
    at executeDispatchesInOrder (react-dom.development.js:483)
    at executeDispatchesAndRelease (react-dom.development.js:581)
fail @ fail.js:2
Jobs__assert @ Jobs.js:47
onClick @ Jobs.js:23
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:461
executeDispatchesInOrder @ react-dom.development.js:483
executeDispatchesAndRelease @ react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
forEachAccumulated @ react-dom.development.js:562
runEventsInBatch @ react-dom.development.js:723
runExtractedEventsInBatch @ react-dom.development.js:732
handleTopLevel @ react-dom.development.js:4476
batchedUpdates$1 @ react-dom.development.js:16659
batchedUpdates @ react-dom.development.js:2131
dispatchEvent @ react-dom.development.js:4555
interactiveUpdates$1 @ react-dom.development.js:16714
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532`

**Comment by mAAdhaTTah** [comment]
I'm currently working on a rewrite of the FE in TS (#277). We've removed tcomb, so this issue shouldn't remain post-rewrite, but I'll validate it again once I finish it.

**Comment by mAAdhaTTah** [comment]
I will mention you are running the development version of the scripts, as production shouldn't have tcomb. Do you have `SCRIPT_DEBUG` enabled?

**Comment by mAAdhaTTah** [comment]
This should be resolved in the latest version (1.1.2) but please reopen if you still have issues.
