### ISSUE TITLE
Repo URL

### ISSUE THREAD

**Issue by szepeviktor** [mAAdhaTTah/WP-Gistpen#30]
Please set repo URL: https://wordpress.org/plugins/wp-gistpen/

**Comment by mAAdhaTTah** [comment]
Not sure what you mean; set repo URL where?

**Comment by szepeviktor** [comment]
![repo url](http://i.snag.gy/qMSMJ.jpg)

**Comment by mAAdhaTTah** [comment]
Hah, done.
