### ISSUE TITLE
Ability to show the Gist link?

### ISSUE THREAD

**Issue by BoweFrankema** [mAAdhaTTah/wp-gistpen#36]
I was wondering if it was possible to show the URL to the Gist automatically? This would be helpful since embedding of a Gistpen is not yet possible. But since they are synced to Gist we could do something like:

Gist Embed Code:
_link to Gist_

**Comment by mAAdhaTTah** [comment]
This should be doable for the next release.

**Comment by mAAdhaTTah** [comment]
I may also include oEmbeds in said release.
