### ISSUE TITLE
Gistpen Inserts broken on Custom Post Types

### ISSUE THREAD

**Issue by BoweFrankema** [mAAdhaTTah/WP-Gistpen#37]
If you're using the GistPen insert button on regular Posts & Pages everything works as expected, but on CPT screens the button stays empty and shows an empty insert window.

<img width="1362" alt="screen shot 2015-12-18 at 13 04 50" src="https://cloud.githubusercontent.com/assets/855037/11896572/f3f1c446-a587-11e5-86c1-6c7a4aaf3b3c.png">

**Comment by mAAdhaTTah** [comment]
All the JS is being refactored to use the WP-API in #38. We've got the editor working; this should be next.

**Comment by mAAdhaTTah** [comment]
This is fixed in `develop`.

**Comment by tripflex** [comment]
If anybody reading this wants to fix this now, in the current released version on WP, just update the `app\Register\Assets\Popup.php` with this:

https://gist.github.com/tripflex/006b07c08b12d9a27432580d3e04dd5c
