### ISSUE TITLE
Support for using in custom post types?

### ISSUE THREAD

**Issue by tripflex** [mAAdhaTTah/wp-gistpen#61]
Seems like I can only get the modal (from tinymce toolbar) to work correctly from regular posts, not from any custom post types.

Error in console is `InsertGistpenDialog is not defined`

Assuming that your custom JS isn't being loaded on the custom post type pages and is why that error shows?

**Comment by tripflex** [comment]
Ahh just saw this should be resolved from #37

**Comment by tripflex** [comment]
Would it be possible to backport this to master?  I know the entire codebase is being refactored, and i'll probably just edit the files myself, but figured i would ask

**Comment by tripflex** [comment]
If anybody reading this wants to fix this now, in the current released version on WP, just update the `app\Register\Assets\Popup.php` with this:

https://gist.github.com/tripflex/006b07c08b12d9a27432580d3e04dd5c

**Comment by mAAdhaTTah** [comment]
Sure, if you want to open a PR against `master` with that edit, I can put it in an updated version. That would also give me an excuse to test the current `master` against the latest version of WordPress and bump the Readme.

**Comment by mAAdhaTTah** [comment]
At this point, we're nearing an alpha for 1.0.0, so I'm not going to bother backporting this. Sorry.
