### ISSUE TITLE
SyntaxError (DOM Exception 12): The string did not match the expected pattern. - settings.js

### ISSUE THREAD

**Issue by miklb** [mAAdhaTTah/wp-gistpen#91]
With latest 1.0.0a.1 & WP 4.8.1 when I navigate to the accounts tab, `wp-admin/wpgp_route` is a 404.

I do have WordPress in a `/wp` directory, not root and `wp-content` in a different directory as well if that helps.

**Comment by miklb** [comment]
I should also add this is on localhost, not sure if the accounts tab requires public URL.

**Comment by mAAdhaTTah** [comment]
Try redownloading it. I had a problem with the JS in the version I uploaded initially.

**Comment by miklb** [comment]
no luck with download.

**Comment by miklb** [comment]
Seeing `gistpens/tiger-in-the-snow-html5/settings-json/?ver=1.0.0-alpha.1` is also a 404 in console errors.

**Comment by mAAdhaTTah** [comment]
Flush rewrites? `wp rewrite flush --hard` if you're using WP-CLI?

**Comment by mAAdhaTTah** [comment]
And what errors are you seeing in the console? This is def a JS error.

**Comment by miklb** [comment]
Tried flushing rewrites, no luck. That's the only error I see in the console.

**Comment by miklb** [comment]
fyi I tried just checking out the repo and 1.0.0a.1 tag but white screened. Didn't see where the error was though. download works fine ¯\_(ツ)_/¯

**Comment by miklb** [comment]
I recall having an issue with json endpoint and WordPress being in a subdirectory of root install. I'll have to look and see how we solved it then.

**Comment by mAAdhaTTah** [comment]
if you clone from the repo, you need to build it yourself, which means node, npm, composer, etc. the .zip handles all of that and ships the built plugin.

the previous version uploaded had this problem. let me rebuild and reupload it and make sure you're getting the latest.

**Comment by mAAdhaTTah** [comment]
Ok, uploaded a new version. Maybe delete the plugin then reupload it?

**Comment by miklb** [comment]
deleted, re-downloaded, re-activated, same error.

I can try the repo and build script if that would help.

**Comment by mAAdhaTTah** [comment]
You are seeing a 404 in the console for the JS, right?

**Comment by miklb** [comment]
the wp-json endpoint I linked to is the 404 in console, and then if I click the accounts tab, it loads my theme 404 for `wp-admin/wpgp_route`

**Comment by mAAdhaTTah** [comment]
The link you're clicking is supposed to be manage by the JavaScript. All of the Gistpen screens are JS/API-driven SPAs, and in this case, the JS is responsible for turning those URLs into the correct links after the page loads, but it appears it isn't. My _guess_ is this is because the JS is either 404ing or otherwise erroring as the settings page starts.

Can you check in the console on the settings page?

**Comment by miklb** [comment]
> Can you check in the console on the settings page?

That is from the wp-gistpen settings page. Clicking the accounts tab doesn't throw any other errors I see.

**Comment by miklb** [comment]
I tested in a local install that does not have WordPress in subdirectory, and same error, so that can probably be ruled out.

**Comment by mAAdhaTTah** [comment]
So when you load up the Settings page, there's no other errors in the console? Open the console then refresh the page; the problem would be on page load. Does the code get highlighted properly?

**Comment by mAAdhaTTah** [comment]
It doesn't really surprise me that the deployment process is still a little wonky though :/.

**Comment by miklb** [comment]
Sorry, no other errors, just the 404 on the json endpoint.

**Comment by mAAdhaTTah** [comment]
That URL isn't the JSON endpoint. That looks like a link to an individual Gistpen Blob. You sure you flushed ur rewrite rules? A similar URL loads [on my site](http://jamesdigioia.com/gistpens/server-side-rendering-with-react/app-js/) but doesn't display correctly.

**Comment by miklb** [comment]
OK, I ran the hard flush again and deleted the existing tables from the plugin.

Now I just get this
`[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (settings-json:1)`

progress?

**Comment by miklb** [comment]
After clicking the Assets tab, I know get a 404 in console for `…/plugins/wp-gistpen/assets/js/content.js?ver=1.0.0-alpha.1`

**Comment by mAAdhaTTah** [comment]
I mean, a bit, although why your JS isn't working doesn't make sense. I just downloaded the zip and it's definitely in there. If you look in your `plugins/wp-gistpen/assets/js` folder, is it there?

**Comment by miklb** [comment]
The file is there, not sure if the versioning is an issue? And just to be sure, I tested in Firefox instead of Safari Tech Preview, same issues.

**Comment by mAAdhaTTah** [comment]
Do you have any web caching (nginx) that should be busted? Or rules like that? If the file's there but not being served, I'm at a loss as to what's going on...

**Comment by miklb** [comment]
hmm. Let me check.

**Comment by mAAdhaTTah** [comment]
I uploaded alpha.2. There isn't anything in there that will necessarily solve this problem, as I don't know the cause yet, but the links no longer go to `wpgp_route` and will instead remain on the same page if they don't work.

**Comment by miklb** [comment]
Still not sure why the json endpoint is 404ing on the local dev version of my personal site, unless because I had tested an older version, there are some gists imported somewhere?

As to testing it on a site I had never synced with, now I'm getting a 404 on `settings.js` but it is definitely in the plugin directory.

**Comment by mAAdhaTTah** [comment]
> Still not sure why the json endpoint is 404ing on the local dev version of my personal site

What's the URL that's 404ing exactly? I don't _think_ this is a JSON endpoint. And what's the full URL that's 404'ing for the settings.js file? Is the JS for the editor loading correctly? And what version of WP you're running?

**Comment by miklb** [comment]
On the site that I had tested `0.5.2` on, the the 404 is `http://miklb.dev/gistpens/tiger-in-the-snow-html5/settings-json/?ver=1.0.0-alpha.2` That title is a gist of mine, so somewhere the plugin it is trying  read a gist? I thought I had cleared everything out of the DB in testing alpha 1, but something I'm missing?

Running 4.8.1 on both sites.

The site I never connected gistpen with my GitHub account, the 404 is on `http://permission.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.2`

Both running locally with nginx.

**Comment by mAAdhaTTah** [comment]
Yeah, so that URL is a post URL, which is similar to the link I posted to my site [here](http://jamesdigioia.com/gistpens/server-side-rendering-with-react/app-js/), which means it's not a JSON endpoint. If you cleaned out your DB before testing alpha.1, then yeah, the post would 404 because you deleted it :D.

The fact that the JS isn't getting served is more confusing/weird, and if you confirm you see the assets in your local folder at that location, then I have no idea what's going on with your setup to cause this issue.

**Comment by miklb** [comment]
In a clean VM running LAMP and 4.8.1, I get a different error in console

```
[Error] SyntaxError (DOM Exception 12): The string did not match the expected pattern.
	querySelector (settings.js:31234)
	(anonymous function) (settings.js:31234)
	(anonymous function) (settings.js:1495)
	_onActivation (settings.js:1463)
	_setActive (settings.js:994)
	_on (settings.js:1037)
	_addToCur (settings.js:3325)
	_add (settings.js:3271)
	_handleMain (settings.js:3566)
	callSubscriber (settings.js:893)
	dispatch (settings.js:962)
	_emitValue (settings.js:1019)
	_handleSubAny (settings.js:3367)
	callSubscriber (settings.js:893)
	dispatch (settings.js:962)
	_emitValue (settings.js:1019)
	value (settings.js:1398)
	(anonymous function) (settings.js:1583)
```

**Comment by mAAdhaTTah** [comment]
At least that's _something_. What browser is this?

**Comment by miklb** [comment]
aha. That's in Safari 11 (tech preview). When I checked the VM with Chrome Canary, it works.

The missing gistpen link is still there on my personal dev site in Chrome however. Any suggestions on how to delete any artifacts in the db I'm missing?

**Comment by mAAdhaTTah** [comment]
> aha. That's in Safari 11 (tech preview). When I checked the VM with Chrome Canary, it works.

Alrighty! I've mostly tested on Chrome (cuz that's what I use), so gotta spend some time on cross-browser testing. Good to know we have a Safari issue, will check that one next.

> The missing gistpen link is still there on my personal dev site in Chrome however. Any suggestions on how to delete any artifacts in the db I'm missing?

What links to that URL?

**Comment by mAAdhaTTah** [comment]
Update the issue name to reflect the current issue.

**Comment by mAAdhaTTah** [comment]
I'm going to chalk up the previous errors to environment issues. Next release will resolve the syntax error in Safari.

**Comment by miklb** [comment]
Understood. Any thoughts on how I could clean out any references to previous gists?

**Comment by mAAdhaTTah** [comment]
You said you cleared out your database, right? If the URL is 404'ing, then it was deleted as you expected. I'm not entirely sure what you're looking for.

**Comment by miklb** [comment]
I haven't re-authorized the app, can't get to that screen, but the app is still somehow finding **my** gists. I'm asking for suggestions on how to do a clean install. Sorry I wasn't clear.

Even in Chrome, I get that 404 error when on the gistpen settings page, preventing me from authorizing.

**Comment by mAAdhaTTah** [comment]
> I haven't re-authorized the app

Re-authorized what app? I'm a bit lost, because there is no authorization from the settings page, nor links to Gists or Gistpens. The authorization is done by creating a Personal Access on GitHub (which I'm thinking should be better documented on that page) and pasting it in the account page. It's not an oAuth flow or anything like that.

**Comment by miklb** [comment]
OK, seems my vernacular is more generic than yours, and my attempts to test the latest version are starting to wear thin on you. I'll step back and wait for a formal release and see if I can figure out where/how to remove all references to the old plugin in my current site.

Sorry for the trouble.

**Comment by mAAdhaTTah** [comment]
No, please, I'm pretty patient, and I don't want to discourage you from continuing to test the plugin :). I'm just confused as to what you're asking specifically. If you'd prefer, my email address is available via my GH profile; that may be easier to resolve. If you do, please send screenshots of what you're seeing.

**Comment by miklb** [comment]
OK, I went through the database again and  removed all rows in`post meta` that contain `_wpgp_*` and only `options` row I can find is for activated.

I also deleted all posts that had a `guid` that contained `gistpens`.

Now I have this error, which is in Chrome Canary

`GET http://miklb.dev/content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3 net::ERR_ABORTED`

Safari returns a 404 for that link.

The file exists in that location.

I've deleted the personal access token from GitHub as well. (I had forgotten it was a token, thus my generic use of authorization).

**Comment by mAAdhaTTah** [comment]
The database tasks you performed and the 404 error you're getting for that URL are highly unlikely to be related. If the asset isn't being served, then it's likely a problem with the environment itself. I'm not sure I can be much help here, tbh, as there are a number of reasons why that could be happening, not all of which are WP-related (e.g. nginx/apache configuration, firewalls, etc.). If the asset is in the folder, and other assets are being served, then I'm kind of at a loss here as to what the cause is without being able to poke at your setup myself.

If it makes you feel any better, when I've experienced problems like this in past, it's almost always some kind of silly facepalm on my part, like I copied the files to the wrong folder, or I'm looking at the wrong place and the files actuallly _aren't_ there, or something of that nature. So I would go about this by rechecking all of the assumptions I have about how the set up is configured and working. That said, we _know_ the plugin is installed and working, cuz you're able to load up the settings page, so that itself rules out a class of potential problems that I thought might be likely culprits here.

We've definitely confirmed the files are in there and are being served properly in another setup, so it's definitely something specific to _this setup_, so that's where I would focus my attention.  I hope that helps; I'm not sure how much more help I can be, as I'm not really a devops guy, but do let me know if you get somewhere with that.

**Comment by miklb** [comment]
For giggles, I fired up a fresh install in a VM using FlyWheel but this time using nginx, and this is the error I receive for the gistpen settings page.

```
AssertionErroractual: falseexpected: truegeneratedMessage: falsemessage: "el is not an HTMLElement"name: "AssertionError"operator: "=="stack: "AssertionError: el is not an HTMLElement↵    at http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:20775:60↵    at http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:18952:27↵    at http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:8188:49↵    at http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:20855:20↵    at FlatMap._add (http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:3271:22)↵    at FlatMap._handleMain (http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:3566:14)↵    at FlatMap._$handleMain (http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:3542:18)↵    at callSubscriber (http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:893:5)↵    at Dispatcher.dispatch (http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:962:7)↵    at AnonymousObservable._emitValue (http://gistpentesting.dev/wp-content/plugins/wp-gistpen/assets/js/settings.js?ver=1.0.0-alpha.3:1019:24)"__proto__: Error
```

**Comment by miklb** [comment]
Here's a link to [Local by FlyWheel](https://local.getflywheel.com) that I used to spin up the tests.
